"""Insert recommendation test events using products that exist in the database.

The old seed used hard-coded Nike/Dell/Xiaomi names that may no longer be in the
catalog. This script samples active products and records UUID product_id values,
so the recommendation jobs can produce rows that import cleanly into PostgreSQL.
"""

from __future__ import annotations

import argparse
import os
import uuid
from dataclasses import dataclass

import psycopg2
import psycopg2.extras


DEFAULT_DATABASE_URL = "postgresql://shopping_user:shopping_password@localhost:5432/shopping"
SEED_SOURCE_PREFIX = "/seed/recommendations"


@dataclass(frozen=True)
class ProductSeed:
    id: str
    name: str
    slug: str
    shop_name: str | None
    category_name: str | None
    price: float


def db_url() -> str:
    return os.getenv("DATABASE_URL", DEFAULT_DATABASE_URL)


def load_products(conn, limit: int) -> list[ProductSeed]:
    query = """
        SELECT
            p.id::text AS id,
            p.name,
            p.slug,
            s.name AS shop_name,
            c.name AS category_name,
            p.price::float AS price
        FROM products p
        LEFT JOIN shop_products sp ON sp.product_id = p.id
        LEFT JOIN shops s ON s.id = sp.shop_id
        LEFT JOIN product_categories c ON c.id = p.category_id
        WHERE p.status = 'active'
          AND p.available_item_count > 0
          AND EXISTS (
              SELECT 1 FROM product_images pi WHERE pi.product_id = p.id
          )
        ORDER BY
            COALESCE(s.name, ''),
            COALESCE(c.name, ''),
            p.name
        LIMIT %s
    """
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(query, (limit,))
        rows = cur.fetchall()
    return [
        ProductSeed(
            id=row["id"],
            name=row["name"],
            slug=row["slug"],
            shop_name=row["shop_name"],
            category_name=row["category_name"],
            price=float(row["price"]),
        )
        for row in rows
    ]


def event_tuple(event_type: str, anonymous_id: str, product: ProductSeed, source_suffix: str):
    return (
        event_type,
        anonymous_id,
        product.id,
        product.name,
        product.slug,
        product.shop_name,
        product.category_name,
        product.price,
        f"{SEED_SOURCE_PREFIX}/{source_suffix}/{product.slug}",
    )


def build_events(products: list[ProductSeed]) -> list[tuple]:
    if len(products) < 6:
        raise RuntimeError(f"Need at least 6 active products with images; found {len(products)}")

    users = [str(uuid.uuid4()) for _ in range(5)]
    events: list[tuple] = []

    # Create overlapping baskets so item similarity has useful co-occurrences.
    profiles = [
        (users[0], [0, 1, 2, 3], [0, 1]),
        (users[1], [1, 2, 3, 4], [2]),
        (users[2], [4, 5, 6, 7], [4, 5] if len(products) > 7 else [4]),
        (users[3], [0, 5, 8, 9], [8] if len(products) > 9 else [5]),
        (users[4], [2, 6, 10, 11], [10] if len(products) > 11 else [2]),
    ]

    for user, view_indexes, conversion_indexes in profiles:
        for idx in view_indexes:
            if idx >= len(products):
                continue
            repeat = 4 if idx in conversion_indexes else 2
            events.extend(
                event_tuple("product_view", user, products[idx], "view")
                for _ in range(repeat)
            )
        for idx in conversion_indexes:
            if idx >= len(products):
                continue
            events.append(event_tuple("add_to_cart", user, products[idx], "cart"))
            events.append(event_tuple("recommendation_click", user, products[idx], "rec-click"))
        if conversion_indexes:
            events.append(event_tuple("order_paid", user, products[conversion_indexes[0]], "order"))

    return events


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed realistic recommendation events")
    parser.add_argument("--limit", type=int, default=18, help="Number of active products to sample")
    parser.add_argument(
        "--keep-existing-seed",
        action="store_true",
        help="Do not delete prior events generated by this script",
    )
    args = parser.parse_args()

    conn = psycopg2.connect(db_url())
    conn.autocommit = True

    products = load_products(conn, args.limit)
    events = build_events(products)

    with conn.cursor() as cur:
        if not args.keep_existing_seed:
            cur.execute(
                "DELETE FROM user_behavior_events WHERE source_page LIKE %s",
                (f"{SEED_SOURCE_PREFIX}%",),
            )

        cur.executemany(
            """
            INSERT INTO user_behavior_events
                (event_type, anonymous_id, product_id, product_name, product_slug,
                 shop_name, category_name, price, source_page)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
            """,
            events,
        )

        cur.execute("SELECT COUNT(*) FROM user_behavior_events")
        total = cur.fetchone()[0]

    conn.close()
    print(f"Inserted {len(events)} UUID-backed seed events from {len(products)} products.")
    print(f"Total events in DB: {total}")


if __name__ == "__main__":
    main()
